/** By YamiY Yaten */
package com.yatensoft.dcbot.core.enumeration;

/**
 * Enum holding channel names of KitchenTableTCGs server
 */
public enum KitchenTableTCGsChannelEnum {
    GENERAL_GENERAL("KITCHEN_TABLE_TCGS_GENERAL_general"),
    GENERAL_RECOMMENDATIONS("KITCHEN_TABLE_TCGS_GENERAL_recommendations"),
    GENERAL_OTHER_SHIT("KITCHEN_TABLE_TCGS_GENERAL_other-shit"),
    ENTERTAINMENT_MEMES("KITCHEN_TABLE_TCGS_ENTERTAINMENT_memes"),
    ENTERTAINMENT_MOVIES_AND_SERIES("KITCHEN_TABLE_TCGS_ENTERTAINMENT_movies-and-series"),
    ENTERTAINMENT_MUSIC("KITCHEN_TABLE_TCGS_ENTERTAINMENT_music"),
    ENTERTAINMENT_REC_MOVIES_AND_SERIES("KITCHEN_TABLE_TCGS_ENTERTAINMENT_rec-movies-and-series"),
    ENTERTAINMENT_REC_MUSIC("KITCHEN_TABLE_TCGS_ENTERTAINMENT_rec-music"),
    FLESH_AND_BLOOD_CHAT("KITCHEN_TABLE_TCGS_FLESH-AND-BLOOD_chat"),
    FLESH_AND_BLOOD_NEWS("KITCHEN_TABLE_TCGS_FLESH-AND-BLOOD_news"),
    FLESH_AND_BLOOD_DECKS("KITCHEN_TABLE_TCGS_FLESH-AND-BLOOD_decks"),
    FLESH_AND_BLOOD_EVENTS("KITCHEN_TABLE_TCGS_FLESH-AND-BLOOD_events"),
    FLESH_AND_BLOOD_TRADING_ROOM("KITCHEN_TABLE_TCGS_FLESH-AND-BLOOD_trading-room"),
    FLESH_AND_BLOOD_ONLINE_PLAY("KITCHEN_TABLE_TCGS_FLESH-AND-BLOOD_online-play"),
    YU_GI_OH_CHAT("KITCHEN_TABLE_TCGS_YU-GI-OH!_chat"),
    YU_GI_OH_NEWS("KITCHEN_TABLE_TCGS_YU-GI-OH!_news"),
    YU_GI_OH_DECKS("KITCHEN_TABLE_TCGS_YU-GI-OH!_decks"),
    YU_GI_OH_EVENTS("KITCHEN_TABLE_TCGS_YU-GI-OH!_events"),
    YU_GI_OH_TRADING_ROOM("KITCHEN_TABLE_TCGS_YU-GI-OH!_trading-room"),
    OTHER_TCGS_CARDFIGHT_VANGUARD("KITCHEN_TABLE_TCGS_OTHER-TCGS_cardfight-vanguard"),
    SAYAKA_BOT_SAYAKA_DOCS("KITCHEN_TABLE_TCGS_SAYAKA_bot-sayaka-docs"),
    SAYAKA_CHANGELOG("KITCHEN_TABLE_TCGS_SAYAKA_changelog"),
    VOICE_GENERAL("KITCHEN_TABLE_TCGS_VOICE_general"),
    VOICE_PLAYROOM("KITCHEN_TABLE_TCGS_VOICE_playroom"),
    VOICE_PLAYROOM_2("KITCHEN_TABLE_TCGS_VOICE_playroom-2"),
    VOICE_PLAYROOM_3("KITCHEN_TABLE_TCGS_VOICE_playroom-3");

    private final String channelKey;

    KitchenTableTCGsChannelEnum(final String channelKey) {
        this.channelKey = channelKey;
    }

    public String getChannelKey() {
        return channelKey;
    }
}
