on:
  workflow_dispatch

name: Build and deploy

jobs:
  build-container:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant permission
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}
          repository: ${{ secrets.DOCKER_HUB_REPOSITORY }}
          tags: latest, ${{ github.run_number }}
